site_name: Coherent data analysis in C++

repo_url: https://github.com/taehyounpark/analogical
repo_name: taehyounpark/analogical


nav:
  - Home:
    - Welcome: index.md
    - Installation: home/installation.md
    - Design goals: home/design.md
  - Features:
      - Basic concepts: features/basic.md
      - Dataflow: features/dataflow/dataflow.md 
      - Columns: 
        - Computation graph: features/column/computation.md
        - Creating columns: features/column/column.md
      - Selections: 
        - Cuts and weights: features/selection/filter.md
        - Branches in cutflow: features/selection/channel.md
        - Joining selections: features/selection/join.md
      - Aggregations: 
        - Creating aggregations: features/aggregation/book.md
        - Filling columns: features/aggregation/fill.md
        - Booking selections: features/aggregation/at.md
        - Accessing results: features/aggregation/result.md
      - Sensitivity analysis: 
        - Applying variations: features/sensitivity/vary.md
        - Accessing variations: features/sensitivity/variation.md
      - Lazy actions: features/lazy.md
      - Implicit multithreading: features/multithread.md
  - Demos:
    - Higgs boson: demo/hww/notebook.md
  - API:
    - dataflow:
      - Constructor: api/dataflow/ctor.md
      - read: api/dataflow/read.md
      - constant: api/dataflow/constant.md
      - define: api/dataflow/define.md
      - filter: api/dataflow/filter.md
      - channel: api/dataflow/channel.md
      - book: api/dataflow/book.md
    - lazy:
      - filter: api/lazy/filter.md
      - channel: api/lazy/channel.md
      - evaluate: api/lazy/evaluate.md
      - apply: api/lazy/apply.md
    - delayed:
      - fill: api/lazy/fill.md
      - at: api/lazy/at.md

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: custom
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css