site_name: Coherent data analysis in C++

repo_url: https://github.com/taehyounpark/queryosity
repo_name: taehyounpark/queryosity

nav:
  - Home:
    - Welcome: index.md
    - Installation: home/installation.md
    - Design goals: home/design.md
  - Concepts:
    - Overview: concepts/overview.md
    - Lazy actions: concepts/lazy.md
    - Columns: concepts/column.md
    - Selections: concepts/selection.md
    - Queries: concepts/query.md
    - Systematic variations: concepts/vary.md
  - User guide: 
    - Cheat sheet: guide/cheatsheet.md
    - Dataflow: guide/dataflow.md 
    - Columns: guide/column.md
    - Selections: guide/selection.md
    - Queries:  guide/query.md
    - Systematic variations: guide/vary.md
  - Examples:
    - Hello World: examples/hello.md
    - Higgs WW: examples/hww.md
  - API:
    - 'dataflow': api/classqueryosity_1_1dataflow.md
    - 'lazy': api/classqueryosity_1_1lazy.md
    - 'lazy::varied': api/classqueryosity_1_1lazy_1_1varied.md
    - 'todo': api/classqueryosity_1_1todo.md
    - 'todo::varied': api/classqueryosity_1_1todo_1_1varied.md
  - ABCs:
    - 'dataset::reader': abc/classqueryosity_1_1dataset_1_1reader.md
    - 'column::reader': abc/classqueryosity_1_1column_1_1reader.md
    - 'column::definition': abc/classqueryosity_1_1column_1_1definition_3_01_ret_07_vals_8_8_8_08_4.md
    - 'query::definition': abc/classqueryosity_1_1query_1_1definition_3_01_t_07_obs_8_8_8_08_4.md

theme:
  name: 'material'
  font:
    text: Inter Tight
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light-blue
      accent: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference

plugins:
  - search:
      enabled: true
  - mkdoxy:
      projects:
        api: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: include/queryosity/interface # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "dataflow.h lazy*.h todo*.h dataset.h dataset_input.h dataset_player.h dataset_column.h column_definition.h counter_logic.h counter_logic.h" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
        abc: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: include/queryosity/interface # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "dataset_reader.h column_reader.h column_definition.h query_definition.h" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
      save-api: .mkdoxy

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true

extra:
  annotate:
    cpp: [.s2] 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
