site_name: Coherent data analysis in C++

repo_url: https://github.com/taehyounpark/analogical
repo_name: taehyounpark/analogical


nav:
  - Home:
    - Welcome: index.md
    - Design goals: home/design.md
    - Installation: home/installation.md
    - Quickstart: home/quickstart.md
  - Features:
      - Basic concepts: features/basic.md
      - Dataflow: features/dataflow/dataflow.md 
      - Columns: 
        - The "computation graph": features/column/computation.md
        - Computing columns: features/column/column.md
      - Selections: 
        - The "cutflow": features/selection/cutflow.md
        - Applying selections: features/selection/selection.md
      - Aggregations: 
        - The "counting experiment": features/aggregation/experiment.md
        - Booking aggregations: features/aggregation/aggregation.md
      - Sensitivity analysis: 
        - Systematic variations: features/sensitivity/variation.md
        - Varying an analysis: features/sensitivity/vary.md
      - Lazy actions: features/lazy.md
      - Implicit multithreading: features/multithread.md
  - Demos:
    - Higgs WW: demo/hww/notebook.md
  - API:
    - dataflow:
      - dataflow: api/dataflow/dataflow.md
      - open: api/dataflow/open.md

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: custom
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.tabs.link

# plugins:
#   - mkdoxy:
#       projects:
#         analogical: # name of project must be alphanumeric + numbers (without spaces)
#           src-dirs: include/ana/interface # path to source code (support multiple paths separated by space) => INPUT
#           full-doc: True # if you want to generate full documentation
#           doxy-cfg: # standard doxygen configuration (key: value)
#             FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
#             RECURSIVE: True # recursive search in source directories
#       save-api: docs/.mkdoxy

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css