name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu_gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ['9', '10', '11', '12', '13']
    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}

    steps:
      - uses: actions/checkout@v3
      - name: Run CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DANALOGICAL_TESTS=ON
      - name: Build
        run: cmake --build build --parallel 4
      - name: Test
        run: cd build ; ctest -j 4 --output-on-failure